services:
  console-service:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/console
    ports:
      - 10426:8080
    environment:
      - TZ=Asia/Shanghai
      - DEFAULT_USERNAME=rainbowrain # 默认管理员账户
      - DEFAULT_PASSWORD=rainbowrain09 # 默认管理员账户
      - API_KEY=sk-KGmV4XCVjX6R9awanrDkViuV4lVQSjJwg5tQGCyhUjOFi6fy # 替换为您的API密钥
      - OpenAIEndpoint=https://api.icerain.love/v1 # OpenAI API端点
      - DEFAULT_IMAGE_GENERATION_MODEL=gemini-2.5-pro # 用于优化图片提示词的基础模型
      - IMAGE_GENERATION_MODEL=imagen-4.0-ultra-generate-preview-06-06 # 用于生成图片的模型列表，逗号分隔
      - CHAT_MODEL=gemini-2.5-pro,gemini-2.5-flash,deepseek-v3,deepseek-r1,gpt-4.1-mini,gpt-4o-mini # 聊天模型列表，逗号分隔
      - DEFAULT_CHAT_MODEL=gemini-2.5-pro # 默认聊天模型
    volumes:
      - ./data:/app/data
